### ISSUE TITLE
Comment about why-not-just-build-a-har-file actually

### ISSUE THREAD

**Issue by soulgalore** [csabapalfi/page-weight#6]
Hey @csabapalfi cool project! So about "tries to build HAR from CDP Network ..." - https://github.com/csabapalfi/page-weight#why-not-just-build-a-har-file actually -  it works for the trace log directly from Chrome, so the problem is probably with how puppeteer is configured (the example in the issue misses events and if I remember correctly has the wrong order). It's not a generic Chrome-har problem :)

Best
Peter

**Comment by csabapalfi** [comment]
@soulgalore aaah, sorry about that, should've read through it more thoroughly updating the readme now.

**Comment by soulgalore** [comment]
thanks :)

**Comment by csabapalfi** [comment]
No problem, thanks for clarifying this!
